version: "3.3"
services:
  athena_ps_db:
    container_name: athena_ps_db
    image: postgres:17
    environment:
      POSTGRES_DB: "athena_db"
      POSTGRES_USER: "athena"
      POSTGRES_PASSWORD: "pswd4athena"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
    - "5432:5432"
    volumes:
      - athenadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athena -d athena_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api-server:
    build: athena-backend/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: "athena_db"
      POSTGRES_USER: "athena"
      POSTGRES_PASSWORD: "pswd4athena"
      POSTGRES_HOST: "athena_ps_db"
      POSTGRES_PORT: 5432
    volumes:
      - ./athena-backend:/app
    command: >
      bash -c "source ./start.sh"
    depends_on:
      - athena_ps_db

volumes:
  athenadb:

