version: "3.8"
services:
  athena_ps_db:
    container_name: athena_ps_db
    image: postgres:17.4-alpine
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - athenadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athena -d athena_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api-server:
    container_name: api-server
    build: api-server/
    working_dir: /app
    command: [ "sh", "-c", "./start.sh" ]
    env_file:
      - .env
    depends_on:
      - athena_ps_db

  frontend:
    build: frontend/
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - api-server

volumes:
  athenadb:

