# Generated by Django 5.1.6 on 2025-07-01 14:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_citizenshiplist_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('places', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Грант на поступление',
                'verbose_name_plural': 'Гранты на поступление',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Колледж',
                'verbose_name_plural': 'Колледжи',
            },
        ),
        migrations.CreateModel(
            name='HowFoundOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information_source', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('patronymic', models.CharField(blank=True, default='', max_length=150)),
                ('job_place', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='PreviousPlaceOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Предыдущее место обучения',
                'verbose_name_plural': 'Предыдущие места обучения',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.AlterModelOptions(
            name='citizenshiplist',
            options={'verbose_name': 'Гражданство', 'verbose_name_plural': 'Гражданства'},
        ),
        migrations.AlterModelOptions(
            name='entrant',
            options={'permissions': ([('view_personal_data', 'Can view personal data'), ('export_entrant_data', 'Can export entrant data')],), 'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterModelOptions(
            name='languageofstudy',
            options={'verbose_name': 'Язык обучения', 'verbose_name_plural': 'Языки обучения'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Национальность', 'verbose_name_plural': 'Национальности'},
        ),
        migrations.AlterModelOptions(
            name='previousplaceofstudytype',
            options={'verbose_name': 'Тип учебного заведения', 'verbose_name_plural': 'Типы учебных заведений'},
        ),
        migrations.AlterModelOptions(
            name='quota',
            options={'verbose_name': 'Квота', 'verbose_name_plural': 'Квоты'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='previous_place_of_study_type',
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='specialty',
        ),
        migrations.AddField(
            model_name='citizenshiplist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citizenshiplist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenshiplist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entrant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entrant',
            name='entrant_phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '999999999'. До 11 цифр.", regex='^\\d{1,11}$')]),
        ),
        migrations.AddField(
            model_name='entrant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrant',
            name='residence_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entrant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='languageofstudy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='languageofstudy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='languageofstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nationality',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nationality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='previousplaceofstudytype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='previousplaceofstudytype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='previousplaceofstudytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quota',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quota',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='individual_identical_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИИН должен содержать 12 цифр', regex='^\\d{12}$')], verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='on_the_budget',
            field=models.BooleanField(default=True, verbose_name='На бюджете'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='quota',
            field=models.ManyToManyField(blank=True, to='admissions.quota'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='study_format',
            field=models.CharField(blank=True, choices=[('Очное обучение', 'Очное обучение'), ('Заочное обучение', 'Заочное обучение')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['name'], name='admissions__name_027110_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['code'], name='admissions__code_9febeb_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['name'], name='admissions__name_ab2976_idx'),
        ),
        migrations.AddField(
            model_name='admissionsgrant',
            name='previous_place_of_study_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.previousplaceofstudytype'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='admissions__name_e33269_idx'),
        ),
        migrations.AddField(
            model_name='admissionsgrant',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.college'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.college'),
        ),
        migrations.AddField(
            model_name='howfoundout',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.college'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['last_name', 'first_name'], name='admissions__last_na_04f7b4_idx'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='parents',
            field=models.ManyToManyField(blank=True, to='admissions.parent'),
        ),
        migrations.AddField(
            model_name='previousplaceofstudy',
            name='previous_place_of_study_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.previousplaceofstudytype'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='previous_place_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.previousplaceofstudy'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.specialty'),
        ),
        migrations.AddField(
            model_name='admissionsgrant',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.qualification'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.qualification'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['college', 'last_name', 'first_name'], name='admissions__college_2fc9de_idx'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['college', 'qualification'], name='admissions__college_d91af0_idx'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['college', 'individual_identical_number'], name='admissions__college_4431eb_idx'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['college'], name='admissions__college_d1d4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='howfoundout',
            index=models.Index(fields=['college'], name='admissions__college_b09594_idx'),
        ),
        migrations.AddIndex(
            model_name='previousplaceofstudy',
            index=models.Index(fields=['previous_place_of_study_type'], name='admissions__previou_ac2dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['code'], name='admissions__code_2155f7_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['specialty'], name='admissions__special_566c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsgrant',
            index=models.Index(fields=['college', 'qualification'], name='admissions__college_42ccec_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsgrant',
            index=models.Index(fields=['qualification'], name='admissions__qualifi_140ab0_idx'),
        ),
    ]
