# Generated by Django 5.1.6 on 2025-07-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_admissionsgrant_college_howfoundout_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrant',
            options={'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
    ]
