# Generated by Django 5.1.6 on 2025-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_entrant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousplaceofstudy',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
