# Generated by Django 5.1.6 on 2025-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_previousplaceofstudy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='how_found_out_about_college',
            field=models.ManyToManyField(blank=True, to='admissions.howfoundout'),
        ),
    ]
