# Generated by Django 5.1.6 on 2025-07-04 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_entrant_how_found_out_about_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '999999999'. До 11 цифр.", regex='^\\d{1,11}$')]),
        ),
    ]
