# Generated by Django 5.1.6 on 2025-07-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_admissionsgrant_language_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsgrant',
            name='language_of_study',
        ),
    ]
