# Generated by Django 5.1.6 on 2025-07-12 12:39

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_remove_admissionsgrant_language_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsgrant',
            name='language_of_study',
            field=models.ForeignKey(blank=True, default=admissions.models.get_default_language_of_study, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.languageofstudy'),
        ),
    ]
