# Generated by Django 5.1.6 on 2025-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_admissionsgrant_language_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsgrant',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
